DROP TABLE IF EXISTS GAMEPIANO;
DROP TABLE IF EXISTS TIPO;
DROP TABLE IF EXISTS ALUMNO;
DROP TABLE IF EXISTS ACTIVIDAD;
DROP TABLE IF EXISTS PROFESORES;
DROP TABLE IF EXISTS JUEGA;


CREATE TABLE PROFESORES(
COD_PROFESOR INT(5) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
MAIL VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL );

CREATE TABLE ACTIVIDAD(
COD_ACT INT(5) AUTO_INCREMENT PRIMARY KEY,
COD_PROFESOR INT(5) NOT NULL, 
COD_TIPO_ACT INT(5) NOT NULL
);

CREATE TABLE ALUMNO(
COD_ALUMNO INT(5) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
USUARIO VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(30) NOT NULL
);

CREATE TABLE TIPO(
COD_TIPO INT(5) AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL);

CREATE TABLE GAMEPIANO(
COD_GAME INT(5) AUTO_INCREMENT PRIMARY KEY,
INTERVARLO_TIME INT(2),
COD_TIPO_ACT INT(5) NOT NULL
);

CREATE TABLE JUEGA(
COD_ALUMNO INT(5),
COD_ACT INT(5),
NOTAS INT(3),
PRIMARY KEY(COD_ALUMNO,COD_ACT));







